Fix NPE
Stacktrace from version 23.1.0 :
java.lang.NullPointerException: Cannot invoke "java.util.List.contains(Object)" because "validExtensionsWithDot" is null

	at org.approvaltests.reporters.GenericDiffReporter.isFileExtensionValid(GenericDiffReporter.java:122)
	at org.approvaltests.reporters.GenericDiffReporter.isFileExtensionHandled(GenericDiffReporter.java:117)
	at org.approvaltests.reporters.GenericDiffReporter.isWorkingInThisEnvironment(GenericDiffReporter.java:104)
	at org.approvaltests.reporters.GenericDiffReporter.report(GenericDiffReporter.java:56)
	at org.approvaltests.reporters.FirstWorkingReporter.report(FirstWorkingReporter.java:21)
	at org.approvaltests.reporters.FirstWorkingReporter.report(FirstWorkingReporter.java:21)
	at org.approvaltests.reporters.FirstWorkingReporter.report(FirstWorkingReporter.java:21)
	at org.approvaltests.reporters.FirstWorkingReporter.report(FirstWorkingReporter.java:21)
	at org.approvaltests.approvers.FileApprover.reportFailure(FileApprover.java:49)
	at org.approvaltests.Approvals.verify(Approvals.java:220)
	at org.approvaltests.Approvals.verify(Approvals.java:183)
	at org.approvaltests.Approvals.verify(Approvals.java:191)
	at org.approvaltests.Approvals.verify(Approvals.java:50)